### ISSUE TITLE
FlexSerial always returns chars available to read.

### ISSUE THREAD

**Issue by ko7eraven** [KurtE/FlexIO_t4#10]
The read function returns characters successively, incrementing the buffer tail index until it equals the buffer head index. However, the available function will always return non zero if head==tail. If head==tail this returns -1. 

int FlexSerial::available(void) {
	uint32_t head, tail;

	head = _rx_buffer_head;
	tail = _rx_buffer_tail;
	if (head >= tail) return RX_BUFFER_SIZE - 1 - head + tail;
	return tail - head - 1;
}

**Comment by neilmendoza** [comment]
Fixed here...

https://github.com/neilmendoza/FlexIO_t4

**Comment by KurtE** [comment]
merged

Thanks
