### ISSUE TITLE
FlexSPI_simple hangs

### ISSUE THREAD

**Issue by SMattsson** [KurtE/FlexIO_t4#2]
When trying to run FlexSPI_simple.ino on my T4 it hangs. No additional hardware or code. If i comment out SPIFLEX.beginTransaction(FlexSPISettings(20000000, MSBFIRST, SPI_MODE0));
with // i get the message "FlexSPI - Mosi pin does not map to flex controller".
I tried some other Teensy pins as specified, but still same message.

**Comment by KurtE** [comment]
Sorry,  did not see this issue. 

There was a wrong test at the start where it should have been if(!_pflex)... 

Appears to run now.  Not sure how complete yet
