### ISSUE TITLE
does not compile for FlexIO2 or FlexIO3

### ISSUE THREAD

**Issue by easone** [KurtE/FlexIO_t4#3]
I get a compile error in FlexIO_t4.cpp when trying to use FlexIO2 or FlexIO3. It seems the pointers to `IRQHandler_FlexIO2` and `IRQHandler_FlexIO3` inside the declarations for `flex2_hardware` and `flex3_hardware` are missing `&` signs.

**Comment by KurtE** [comment]
Thanks, 

For some reason it was compiling fine on my machine without the &, but yes should be pointer to... 

I pushed up the changes as mentioned. 

Thanks again
