### ISSUE TITLE
FlexSerial_Transmit.ino hangs T4.1

### ISSUE THREAD

**Issue by PowerBroker2** [KurtE/FlexIO_t4#4]
No compiling issues, it simply hangs. The example sketch was unedited and no hardware was attached to pin 2 on my T4.1

**Comment by KurtE** [comment]
Thanks, 

Should be fixed now.

Try syncing up and see

**Comment by KurtE** [comment]
Any luck?  I just pushed up more changes here that might help.

**Comment by PowerBroker2** [comment]
Sorry, I lost hope for this and found a work around. I think I wanted to use this lib to interface with an FRSky pitot device, but after having trouble with it, I decided to rip off the pressure sensor and interface with it directly - no need for serial comms anymore. Thanks though!
