### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by branko623** [KurtE/FlexIO_t4#5]
`/home/harambe623/Arduino/libraries/FlexIO_t4/FlexIOSPI.cpp: In member function 'bool FlexIOSPI::begin()':
/home/harambe623/Arduino/libraries/FlexIO_t4/FlexIOSPI.cpp:136:37: error: 'fastio' was not declared in this scope
  *(portControlRegister(_mosiPin)) = fastio;`

happens upon compiling in arduino IDE

**Comment by branko623** [comment]
Appears like the latest change to that file broke it, as commit hash e1a04cba944ae7812d0a1378d58cd5e337ace943 works fine

**Comment by KurtE** [comment]
Sorry for some reason when I did the commit last time the one line with the definition did not make it in??? 

Code updated.

Thanks
